sudo: required
language: node_js
node_js:
  - "6.1"
services:
  - docker
before_install:
  - docker pull mcin/cbrain_travis:dev
  - docker run -d -v "`pwd -P`":/home/cbrain/cbrain_travis --name "cb_travis" mcin/cbrain_travis:dev
  - docker ps -a 
“scripts”: {
  "test": "make test"
}
