language: node_js
node_js:
  - "6.1"
before_install: 
  # Install Vagrant
  - sudo apt-get update -q
  - sudo apt-get install -q virtualbox --fix-missing
  - wget -nv https://releases.hashicorp.com/vagrant/2.1.4/vagrant_2.1.4_x86_64.deb
  - sudo dpkg -i vagrant_2.1.4_x86_64.deb
  - vagrant -v

  # Start vagrant
  - cd cbrain-vagrant
  - vagrant plugin install vagrant-vbguest
  - vagrant plugin install vagrant-disksize
  - modprobe vboxdrv
  - vagrant up
  - vagrant ssh
  - cd cbrain/BrainPortal
  - rails server puma -b 0.0.0.0 -p 3000 -e development

install:
  - npm install
scripts: {
  "test": "make test"
}
