sudo: required
language: node_js
node_js:
  - "iojs"
  - "6.1"
services:
  - docker
before_install:
  - docker pull mcin/cbrain_travisi:dev
  - docker run -d -v "`pwd -P`":/home/cbrain/cbrain_travis --name "mcin/cbrain_travis"
  
“scripts”: {
  "test": "make test"
}
