sudo: required
language: node_js
node_js:
  - "6.1"
services:
  - docker
before_install:
  - docker pull mcin/cbrain_travis:dev
  - docker run -d -p 127.0.0.1:3001:80 -v "`pwd -P`":/home/cbrain/cbrain_travis --name "cb_travis" mcin/cbrain_travis:dev
  - docker hostname
  - docker ps -a 
  - docker logs cb_travis --follow
“scripts”: {
  "test": "make test"
}
