/**
 * CBRAIN API
 * Interface to control CBRAIN operations
 *
 * OpenAPI spec version: 4.5.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && false) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.CbrainApi) {
      root.CbrainApi = {};
    }
    root.CbrainApi.Bourreau = factory(root.CbrainApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Bourreau model module.
   * @module model/Bourreau
   * @version 4.5.1
   */

  /**
   * Constructs a new <code>Bourreau</code>.
   * @alias module:model/Bourreau
   * @class
   */
  var exports = function() {
    var _this = this;








  };

  /**
   * Constructs a <code>Bourreau</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Bourreau} obj Optional instance to populate.
   * @return {module:model/Bourreau} The populated <code>Bourreau</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('user_id')) {
        obj['user_id'] = ApiClient.convertToType(data['user_id'], 'Number');
      }
      if (data.hasOwnProperty('group_id')) {
        obj['group_id'] = ApiClient.convertToType(data['group_id'], 'Number');
      }
      if (data.hasOwnProperty('online')) {
        obj['online'] = ApiClient.convertToType(data['online'], 'String');
      }
      if (data.hasOwnProperty('read_only')) {
        obj['read_only'] = ApiClient.convertToType(data['read_only'], 'String');
      }
      if (data.hasOwnProperty('description')) {
        obj['description'] = ApiClient.convertToType(data['description'], 'String');
      }
    }
    return obj;
  }

  /**
   * Unique numerical ID for the bourreau.
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * Name given by the creator to the bourreau.
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * ID of the creator of the bourreau.
   * @member {Number} user_id
   */
  exports.prototype['user_id'] = undefined;
  /**
   * ID of the group allowed to use the bourreau.
   * @member {Number} group_id
   */
  exports.prototype['group_id'] = undefined;
  /**
   * online
   * @member {String} online
   */
  exports.prototype['online'] = undefined;
  /**
   * Specifies whether the bourreau is read-only or can be modified.
   * @member {String} read_only
   */
  exports.prototype['read_only'] = undefined;
  /**
   * Description of the bourreau.
   * @member {String} description
   */
  exports.prototype['description'] = undefined;



  return exports;
}));


