/**
 * CBRAIN API
 * REST API for interacting with the CBRAIN Platform
 *
 * OpenAPI spec version: 5.0.2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.CbrainApi) {
      root.CbrainApi = {};
    }
    root.CbrainApi.CbrainTask = factory(root.CbrainApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The CbrainTask model module.
   * @module model/CbrainTask
   * @version 5.0.2
   */

  /**
   * Constructs a new <code>CbrainTask</code>.
   * @alias module:model/CbrainTask
   * @class
   * @param toolId {Number} 
   * @param cbrainTask {Object} 
   */
  var exports = function(toolId, cbrainTask) {
    var _this = this;

    _this['tool_id'] = toolId;
    _this['cbrain_task'] = cbrainTask;
  };

  /**
   * Constructs a <code>CbrainTask</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CbrainTask} obj Optional instance to populate.
   * @return {module:model/CbrainTask} The populated <code>CbrainTask</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('tool_id')) {
        obj['tool_id'] = ApiClient.convertToType(data['tool_id'], 'Number');
      }
      if (data.hasOwnProperty('cbrain_task')) {
        obj['cbrain_task'] = ApiClient.convertToType(data['cbrain_task'], Object);
      }
    }
    return obj;
  }

  /**
   * @member {Number} tool_id
   */
  exports.prototype['tool_id'] = undefined;
  /**
   * @member {Object} cbrain_task
   */
  exports.prototype['cbrain_task'] = undefined;



  return exports;
}));


