/**
 * CBRAIN API
 * Interface to control CBRAIN operations
 *
 * OpenAPI spec version: 4.5.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.CbrainApi) {
      root.CbrainApi = {};
    }
    root.CbrainApi.DataProvider = factory(root.CbrainApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The DataProvider model module.
   * @module model/DataProvider
   * @version 4.5.1
   */

  /**
   * Constructs a new <code>DataProvider</code>.
   * @alias module:model/DataProvider
   * @class
   */
  var exports = function() {
    var _this = this;












  };

  /**
   * Constructs a <code>DataProvider</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DataProvider} obj Optional instance to populate.
   * @return {module:model/DataProvider} The populated <code>DataProvider</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('type')) {
        obj['type'] = ApiClient.convertToType(data['type'], 'String');
      }
      if (data.hasOwnProperty('user_id')) {
        obj['user_id'] = ApiClient.convertToType(data['user_id'], 'Number');
      }
      if (data.hasOwnProperty('group_id')) {
        obj['group_id'] = ApiClient.convertToType(data['group_id'], 'Number');
      }
      if (data.hasOwnProperty('online')) {
        obj['online'] = ApiClient.convertToType(data['online'], 'String');
      }
      if (data.hasOwnProperty('read_only')) {
        obj['read_only'] = ApiClient.convertToType(data['read_only'], 'String');
      }
      if (data.hasOwnProperty('description')) {
        obj['description'] = ApiClient.convertToType(data['description'], 'String');
      }
      if (data.hasOwnProperty('time_of_death')) {
        obj['time_of_death'] = ApiClient.convertToType(data['time_of_death'], 'String');
      }
      if (data.hasOwnProperty('not_syncable')) {
        obj['not_syncable'] = ApiClient.convertToType(data['not_syncable'], 'String');
      }
      if (data.hasOwnProperty('time_zone')) {
        obj['time_zone'] = ApiClient.convertToType(data['time_zone'], 'String');
      }
    }
    return obj;
  }

  /**
   * Unique ID for the Data Provider.
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * Name of the Data Provider.
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * Type of Data Provider, which usually indicates whether it is a local Data Provider, has a flat internal directory structure, or is meant for file uploading to CBRAIN.
   * @member {String} type
   */
  exports.prototype['type'] = undefined;
  /**
   * Creator and owner of the Data Provider.
   * @member {Number} user_id
   */
  exports.prototype['user_id'] = undefined;
  /**
   * ID of the group that has access to this Data Provider.
   * @member {Number} group_id
   */
  exports.prototype['group_id'] = undefined;
  /**
   * Boolean variable that indicates whether the system hosting the Data Provider is accessible.
   * @member {String} online
   */
  exports.prototype['online'] = undefined;
  /**
   * Boolean variable that indicates whether the Data Provider can be written to.
   * @member {String} read_only
   */
  exports.prototype['read_only'] = undefined;
  /**
   * Description of the Data Provider.
   * @member {String} description
   */
  exports.prototype['description'] = undefined;
  /**
   * The time, in the time zone of the system that hosts the Data Provider, that the Data Provider last successfully transmitted.
   * @member {String} time_of_death
   */
  exports.prototype['time_of_death'] = undefined;
  /**
   * Boolean variable that indicates that the data residing on the Data Provider is not available to be transferred to an execution server's cache.
   * @member {String} not_syncable
   */
  exports.prototype['not_syncable'] = undefined;
  /**
   * Time zone of the system that hosts the Data Provider.
   * @member {String} time_zone
   */
  exports.prototype['time_zone'] = undefined;



  return exports;
}));


