/**
 * CBRAIN API
 * REST API for interacting with the CBRAIN Platform
 *
 * OpenAPI spec version: 5.0.2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Userfile'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Userfile'));
  } else {
    // Browser globals (root is window)
    if (!root.CbrainApi) {
      root.CbrainApi = {};
    }
    root.CbrainApi.InlineResponse2002 = factory(root.CbrainApi.ApiClient, root.CbrainApi.Userfile);
  }
}(this, function(ApiClient, Userfile) {
  'use strict';




  /**
   * The InlineResponse2002 model module.
   * @module model/InlineResponse2002
   * @version 5.0.2
   */

  /**
   * Constructs a new <code>InlineResponse2002</code>.
   * @alias module:model/InlineResponse2002
   * @class
   */
  var exports = function() {
    var _this = this;








  };

  /**
   * Constructs a <code>InlineResponse2002</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse2002} obj Optional instance to populate.
   * @return {module:model/InlineResponse2002} The populated <code>InlineResponse2002</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('notice')) {
        obj['notice'] = ApiClient.convertToType(data['notice'], 'String');
      }
      if (data.hasOwnProperty('error')) {
        obj['error'] = ApiClient.convertToType(data['error'], 'String');
      }
      if (data.hasOwnProperty('newly_registered_userfiles')) {
        obj['newly_registered_userfiles'] = ApiClient.convertToType(data['newly_registered_userfiles'], [Userfile]);
      }
      if (data.hasOwnProperty('previously_registered_userfiles')) {
        obj['previously_registered_userfiles'] = ApiClient.convertToType(data['previously_registered_userfiles'], [Userfile]);
      }
      if (data.hasOwnProperty('userfiles_in_transit')) {
        obj['userfiles_in_transit'] = ApiClient.convertToType(data['userfiles_in_transit'], [Userfile]);
      }
      if (data.hasOwnProperty('num_unregistered')) {
        obj['num_unregistered'] = ApiClient.convertToType(data['num_unregistered'], 'Number');
      }
      if (data.hasOwnProperty('num_erased')) {
        obj['num_erased'] = ApiClient.convertToType(data['num_erased'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {String} notice
   */
  exports.prototype['notice'] = undefined;
  /**
   * @member {String} error
   */
  exports.prototype['error'] = undefined;
  /**
   * @member {Array.<module:model/Userfile>} newly_registered_userfiles
   */
  exports.prototype['newly_registered_userfiles'] = undefined;
  /**
   * @member {Array.<module:model/Userfile>} previously_registered_userfiles
   */
  exports.prototype['previously_registered_userfiles'] = undefined;
  /**
   * @member {Array.<module:model/Userfile>} userfiles_in_transit
   */
  exports.prototype['userfiles_in_transit'] = undefined;
  /**
   * @member {Number} num_unregistered
   */
  exports.prototype['num_unregistered'] = undefined;
  /**
   * @member {Number} num_erased
   */
  exports.prototype['num_erased'] = undefined;



  return exports;
}));


