/**
 * CBRAIN API
 * Interface to control CBRAIN operations
 *
 * OpenAPI spec version: 4.5.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && false) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.CbrainApi) {
      root.CbrainApi = {};
    }
    root.CbrainApi.Parameters = factory(root.CbrainApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Parameters model module.
   * @module model/Parameters
   * @version 4.5.1
   */

  /**
   * Constructs a new <code>Parameters</code>.
   * @alias module:model/Parameters
   * @class
   * @param authenticityToken {String} The token returned by /session/new
   * @param params {Object} 
   */
  var exports = function(authenticityToken, params) {
    var _this = this;

    _this['authenticity_token'] = authenticityToken;
    _this['params'] = params;
  };

  /**
   * Constructs a <code>Parameters</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Parameters} obj Optional instance to populate.
   * @return {module:model/Parameters} The populated <code>Parameters</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('authenticity_token')) {
        obj['authenticity_token'] = ApiClient.convertToType(data['authenticity_token'], 'String');
      }
      if (data.hasOwnProperty('params')) {
        obj['params'] = ApiClient.convertToType(data['params'], Object);
      }
    }
    return obj;
  }

  /**
   * The token returned by /session/new
   * @member {String} authenticity_token
   */
  exports.prototype['authenticity_token'] = undefined;
  /**
   * @member {Object} params
   */
  exports.prototype['params'] = undefined;



  return exports;
}));


