/**
 * CBRAIN API
 * Interface to control CBRAIN operations
 *
 * OpenAPI spec version: 4.5.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.CbrainApi) {
      root.CbrainApi = {};
    }
    root.CbrainApi.Userfile = factory(root.CbrainApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Userfile model module.
   * @module model/Userfile
   * @version 4.5.1
   */

  /**
   * Constructs a new <code>Userfile</code>.
   * @alias module:model/Userfile
   * @class
   */
  var exports = function() {
    var _this = this;















  };

  /**
   * Constructs a <code>Userfile</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Userfile} obj Optional instance to populate.
   * @return {module:model/Userfile} The populated <code>Userfile</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('size')) {
        obj['size'] = ApiClient.convertToType(data['size'], 'Number');
      }
      if (data.hasOwnProperty('user_id')) {
        obj['user_id'] = ApiClient.convertToType(data['user_id'], 'Number');
      }
      if (data.hasOwnProperty('parent_id')) {
        obj['parent_id'] = ApiClient.convertToType(data['parent_id'], 'Number');
      }
      if (data.hasOwnProperty('type')) {
        obj['type'] = ApiClient.convertToType(data['type'], 'String');
      }
      if (data.hasOwnProperty('group_id')) {
        obj['group_id'] = ApiClient.convertToType(data['group_id'], 'Number');
      }
      if (data.hasOwnProperty('data_provider_id')) {
        obj['data_provider_id'] = ApiClient.convertToType(data['data_provider_id'], 'Number');
      }
      if (data.hasOwnProperty('group_writable')) {
        obj['group_writable'] = ApiClient.convertToType(data['group_writable'], 'String');
      }
      if (data.hasOwnProperty('num_files')) {
        obj['num_files'] = ApiClient.convertToType(data['num_files'], 'Number');
      }
      if (data.hasOwnProperty('hidden')) {
        obj['hidden'] = ApiClient.convertToType(data['hidden'], 'String');
      }
      if (data.hasOwnProperty('immutable')) {
        obj['immutable'] = ApiClient.convertToType(data['immutable'], 'String');
      }
      if (data.hasOwnProperty('archived')) {
        obj['archived'] = ApiClient.convertToType(data['archived'], 'String');
      }
      if (data.hasOwnProperty('description')) {
        obj['description'] = ApiClient.convertToType(data['description'], 'String');
      }
    }
    return obj;
  }

  /**
   * ID number of the file.
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * Name of the file that the Userfile represents
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * Number of bytes used to store the file.
   * @member {Number} size
   */
  exports.prototype['size'] = undefined;
  /**
   * ID of the owner of the file.
   * @member {Number} user_id
   */
  exports.prototype['user_id'] = undefined;
  /**
   * ID of the parent Userfile, if any exists, or null otherwise.
   * @member {Number} parent_id
   */
  exports.prototype['parent_id'] = undefined;
  /**
   * Type of the file. This is important in determining what tools can be run on the file. The most generic file types, are the Single File, which represents one file, and the File Collection, which represents a directory full of files.
   * @member {String} type
   */
  exports.prototype['type'] = undefined;
  /**
   * ID of the group that owns the file, which determines its visibility status.
   * @member {Number} group_id
   */
  exports.prototype['group_id'] = undefined;
  /**
   * ID of the Data Provider that is hosting the persistent copy of the file. It may exist in caches across the systems that make up CBRAIN, as copies of the file are made in order to run scientific programs on them on remote systems.
   * @member {Number} data_provider_id
   */
  exports.prototype['data_provider_id'] = undefined;
  /**
   * Boolean variable that specifies whether members of the owner group have access to modify or overwrite the file.
   * @member {String} group_writable
   */
  exports.prototype['group_writable'] = undefined;
  /**
   * Number of files that the Userfiles represents. For Single Files, this is always 1.
   * @member {Number} num_files
   */
  exports.prototype['num_files'] = undefined;
  /**
   * Boolean variable that specifies whether this file is hidden or not in the user interface.
   * @member {String} hidden
   */
  exports.prototype['hidden'] = undefined;
  /**
   * Boolean variable that specifies whether any user can modify the contents of the file.
   * @member {String} immutable
   */
  exports.prototype['immutable'] = undefined;
  /**
   * Boolean variable that specifies whether the file is available, uncompressed, or has been archived.
   * @member {String} archived
   */
  exports.prototype['archived'] = undefined;
  /**
   * Description of the file.
   * @member {String} description
   */
  exports.prototype['description'] = undefined;



  return exports;
}));


