/**
 * CBRAIN API
 * Interface to control CBRAIN operations
 *
 * OpenAPI spec version: 4.5.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && false) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Bourreau'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/Bourreau'));
  } else {
    // Browser globals (root is window)
    if (!root.CbrainApi) {
      root.CbrainApi = {};
    }
    root.CbrainApi.BourreauApi = factory(root.CbrainApi.ApiClient, root.CbrainApi.Bourreau);
  }
}(this, function(ApiClient, Bourreau) {
  'use strict';

  /**
   * Bourreau service.
   * @module api/BourreauApi
   * @version 4.5.1
   */

  /**
   * Constructs a new BourreauApi. 
   * @alias module:api/BourreauApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the bourreauxGet operation.
     * @callback module:api/BourreauApi~bourreauxGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/Bourreau>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get a list of the Bourreaux available to be used by the current user.
     * This method returns a list of Bourreau objects. 
     * @param {module:api/BourreauApi~bourreauxGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/Bourreau>}
     */
    this.bourreauxGet = function(callback) {
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['BrainPortalSession'];
      var contentTypes = [];
      var accepts = ['application/json', 'application/xml'];
      var returnType = [Bourreau];

      return this.apiClient.callApi(
        '/bourreaux', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the bourreauxIdGet operation.
     * @callback module:api/BourreauApi~bourreauxIdGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Bourreau} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get information about a Bourreau.
     * This method returns a single Bourreau object based on the ID parameter. 
     * @param {Number} id ID of the Bourreau to get information on.
     * @param {module:api/BourreauApi~bourreauxIdGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Bourreau}
     */
    this.bourreauxIdGet = function(id, callback) {
      var postBody = null;

      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling bourreauxIdGet");
      }


      var pathParams = {
        'id': id
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['BrainPortalSession'];
      var contentTypes = [];
      var accepts = ['application/json', 'application/xml'];
      var returnType = Bourreau;

      return this.apiClient.callApi(
        '/bourreaux/{id}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
