/**
 * CBRAIN API
 * Interface to control CBRAIN operations
 *
 * OpenAPI spec version: 4.5.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ToolConfig'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/ToolConfig'));
  } else {
    // Browser globals (root is window)
    if (!root.CbrainApi) {
      root.CbrainApi = {};
    }
    root.CbrainApi.ToolConfigsApi = factory(root.CbrainApi.ApiClient, root.CbrainApi.ToolConfig);
  }
}(this, function(ApiClient, ToolConfig) {
  'use strict';

  /**
   * ToolConfigs service.
   * @module api/ToolConfigsApi
   * @version 4.5.1
   */

  /**
   * Constructs a new ToolConfigsApi. 
   * @alias module:api/ToolConfigsApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the toolConfigsGet operation.
     * @callback module:api/ToolConfigsApi~toolConfigsGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/ToolConfig>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get a list of tool versions installed.
     * This method returns a list of tool config objects. 
     * @param {module:api/ToolConfigsApi~toolConfigsGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/ToolConfig>}
     */
    this.toolConfigsGet = function(callback) {
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['BrainPortalSession'];
      var contentTypes = [];
      var accepts = ['application/json', 'application/xml'];
      var returnType = [ToolConfig];

      return this.apiClient.callApi(
        '/tool_configs', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the toolConfigsIdGet operation.
     * @callback module:api/ToolConfigsApi~toolConfigsIdGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ToolConfig} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get information about a particular tool configuration
     * Returns the information about how a particular configuration of a tool on an execution server. 
     * @param {Number} id the ID of the configuration
     * @param {module:api/ToolConfigsApi~toolConfigsIdGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ToolConfig}
     */
    this.toolConfigsIdGet = function(id, callback) {
      var postBody = null;

      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling toolConfigsIdGet");
      }


      var pathParams = {
        'id': id
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['BrainPortalSession'];
      var contentTypes = [];
      var accepts = ['application/json', 'application/xml'];
      var returnType = ToolConfig;

      return this.apiClient.callApi(
        '/tool_configs/{id}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
