/**
 * CBRAIN API
 * REST API for interacting with the CBRAIN Platform
 *
 * OpenAPI spec version: 5.0.2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CbrainApi);
  }
}(this, function(expect, CbrainApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CbrainApi.InlineResponse2002();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('InlineResponse2002', function() {
    it('should create an instance of InlineResponse2002', function() {
      // uncomment below and update the code to test InlineResponse2002
      //var instane = new CbrainApi.InlineResponse2002();
      //expect(instance).to.be.a(CbrainApi.InlineResponse2002);
    });

    it('should have the property notice (base name: "notice")', function() {
      // uncomment below and update the code to test the property notice
      //var instane = new CbrainApi.InlineResponse2002();
      //expect(instance).to.be();
    });

    it('should have the property error (base name: "error")', function() {
      // uncomment below and update the code to test the property error
      //var instane = new CbrainApi.InlineResponse2002();
      //expect(instance).to.be();
    });

    it('should have the property newlyRegisteredUserfiles (base name: "newly_registered_userfiles")', function() {
      // uncomment below and update the code to test the property newlyRegisteredUserfiles
      //var instane = new CbrainApi.InlineResponse2002();
      //expect(instance).to.be();
    });

    it('should have the property previouslyRegisteredUserfiles (base name: "previously_registered_userfiles")', function() {
      // uncomment below and update the code to test the property previouslyRegisteredUserfiles
      //var instane = new CbrainApi.InlineResponse2002();
      //expect(instance).to.be();
    });

    it('should have the property userfilesInTransit (base name: "userfiles_in_transit")', function() {
      // uncomment below and update the code to test the property userfilesInTransit
      //var instane = new CbrainApi.InlineResponse2002();
      //expect(instance).to.be();
    });

    it('should have the property numUnregistered (base name: "num_unregistered")', function() {
      // uncomment below and update the code to test the property numUnregistered
      //var instane = new CbrainApi.InlineResponse2002();
      //expect(instance).to.be();
    });

    it('should have the property numErased (base name: "num_erased")', function() {
      // uncomment below and update the code to test the property numErased
      //var instane = new CbrainApi.InlineResponse2002();
      //expect(instance).to.be();
    });

  });

}));
