/**
 * CBRAIN API
 * REST API for interacting with the CBRAIN Platform
 *
 * OpenAPI spec version: 5.0.2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CbrainApi);
  }
}(this, function(expect, CbrainApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CbrainApi.ToolConfig();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ToolConfig', function() {
    it('should create an instance of ToolConfig', function() {
      // uncomment below and update the code to test ToolConfig
      //var instane = new CbrainApi.ToolConfig();
      //expect(instance).to.be.a(CbrainApi.ToolConfig);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new CbrainApi.ToolConfig();
      //expect(instance).to.be();
    });

    it('should have the property versionName (base name: "version_name")', function() {
      // uncomment below and update the code to test the property versionName
      //var instane = new CbrainApi.ToolConfig();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instane = new CbrainApi.ToolConfig();
      //expect(instance).to.be();
    });

    it('should have the property toolId (base name: "tool_id")', function() {
      // uncomment below and update the code to test the property toolId
      //var instane = new CbrainApi.ToolConfig();
      //expect(instance).to.be();
    });

    it('should have the property bourreauId (base name: "bourreau_id")', function() {
      // uncomment below and update the code to test the property bourreauId
      //var instane = new CbrainApi.ToolConfig();
      //expect(instance).to.be();
    });

    it('should have the property envArray (base name: "env_array")', function() {
      // uncomment below and update the code to test the property envArray
      //var instane = new CbrainApi.ToolConfig();
      //expect(instance).to.be();
    });

    it('should have the property scriptPrologue (base name: "script_prologue")', function() {
      // uncomment below and update the code to test the property scriptPrologue
      //var instane = new CbrainApi.ToolConfig();
      //expect(instance).to.be();
    });

    it('should have the property groupId (base name: "group_id")', function() {
      // uncomment below and update the code to test the property groupId
      //var instane = new CbrainApi.ToolConfig();
      //expect(instance).to.be();
    });

    it('should have the property ncpus (base name: "ncpus")', function() {
      // uncomment below and update the code to test the property ncpus
      //var instane = new CbrainApi.ToolConfig();
      //expect(instance).to.be();
    });

  });

}));
