/**
 * CBRAIN API
 * Interface to control CBRAIN operations
 *
 * OpenAPI spec version: 4.5.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CbrainApi);
  }
}(this, function(expect, CbrainApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CbrainApi.Userfile();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Userfile', function() {
    it('should create an instance of Userfile', function() {
      // uncomment below and update the code to test Userfile
      //var instane = new CbrainApi.Userfile();
      //expect(instance).to.be.a(CbrainApi.Userfile);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new CbrainApi.Userfile();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instane = new CbrainApi.Userfile();
      //expect(instance).to.be();
    });

    it('should have the property size (base name: "size")', function() {
      // uncomment below and update the code to test the property size
      //var instane = new CbrainApi.Userfile();
      //expect(instance).to.be();
    });

    it('should have the property userId (base name: "user_id")', function() {
      // uncomment below and update the code to test the property userId
      //var instane = new CbrainApi.Userfile();
      //expect(instance).to.be();
    });

    it('should have the property parentId (base name: "parent_id")', function() {
      // uncomment below and update the code to test the property parentId
      //var instane = new CbrainApi.Userfile();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instane = new CbrainApi.Userfile();
      //expect(instance).to.be();
    });

    it('should have the property groupId (base name: "group_id")', function() {
      // uncomment below and update the code to test the property groupId
      //var instane = new CbrainApi.Userfile();
      //expect(instance).to.be();
    });

    it('should have the property dataProviderId (base name: "data_provider_id")', function() {
      // uncomment below and update the code to test the property dataProviderId
      //var instane = new CbrainApi.Userfile();
      //expect(instance).to.be();
    });

    it('should have the property groupWritable (base name: "group_writable")', function() {
      // uncomment below and update the code to test the property groupWritable
      //var instane = new CbrainApi.Userfile();
      //expect(instance).to.be();
    });

    it('should have the property numFiles (base name: "num_files")', function() {
      // uncomment below and update the code to test the property numFiles
      //var instane = new CbrainApi.Userfile();
      //expect(instance).to.be();
    });

    it('should have the property hidden (base name: "hidden")', function() {
      // uncomment below and update the code to test the property hidden
      //var instane = new CbrainApi.Userfile();
      //expect(instance).to.be();
    });

    it('should have the property immutable (base name: "immutable")', function() {
      // uncomment below and update the code to test the property immutable
      //var instane = new CbrainApi.Userfile();
      //expect(instance).to.be();
    });

    it('should have the property archived (base name: "archived")', function() {
      // uncomment below and update the code to test the property archived
      //var instane = new CbrainApi.Userfile();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instane = new CbrainApi.Userfile();
      //expect(instance).to.be();
    });

  });

}));
