/**
 * CBRAIN API
 * Interface to control CBRAIN operations
 *
 * OpenAPI spec version: 4.5.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CbrainApi);
  }
}(this, function(expect, CbrainApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CbrainApi.User();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('User', function() {
    it('should create an instance of User', function() {
      // uncomment below and update the code to test User
      //var instane = new CbrainApi.User();
      //expect(instance).to.be.a(CbrainApi.User);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new CbrainApi.User();
      //expect(instance).to.be();
    });

    it('should have the property login (base name: "login")', function() {
      // uncomment below and update the code to test the property login
      //var instane = new CbrainApi.User();
      //expect(instance).to.be();
    });

    it('should have the property password (base name: "password")', function() {
      // uncomment below and update the code to test the property password
      //var instane = new CbrainApi.User();
      //expect(instance).to.be();
    });

    it('should have the property passwordConfirmation (base name: "password_confirmation")', function() {
      // uncomment below and update the code to test the property passwordConfirmation
      //var instane = new CbrainApi.User();
      //expect(instance).to.be();
    });

    it('should have the property fullName (base name: "full_name")', function() {
      // uncomment below and update the code to test the property fullName
      //var instane = new CbrainApi.User();
      //expect(instance).to.be();
    });

    it('should have the property email (base name: "email")', function() {
      // uncomment below and update the code to test the property email
      //var instane = new CbrainApi.User();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instane = new CbrainApi.User();
      //expect(instance).to.be();
    });

    it('should have the property siteId (base name: "site_id")', function() {
      // uncomment below and update the code to test the property siteId
      //var instane = new CbrainApi.User();
      //expect(instance).to.be();
    });

    it('should have the property lastConnectedAt (base name: "last_connected_at")', function() {
      // uncomment below and update the code to test the property lastConnectedAt
      //var instane = new CbrainApi.User();
      //expect(instance).to.be();
    });

    it('should have the property accountLocked (base name: "account_locked")', function() {
      // uncomment below and update the code to test the property accountLocked
      //var instane = new CbrainApi.User();
      //expect(instance).to.be();
    });

  });

}));
