/**
 * CBRAIN API
 * REST API for interacting with the CBRAIN Platform
 *
 * OpenAPI spec version: 5.0.2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CbrainApi);
  }
}(this, function(expect, CbrainApi) {
  'use strict';

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('BourreauApi', function() {
    let instance;

    beforeEach(function() {
      instance = new CbrainApi.BourreauApi();
    });

    it('should call bourreauxGet successfully', function(done) {
      instance.bourreauxGet(function(error,data,response) {
        if (error) throw error;
        // The status code should be 200 
        expect(response.statusCode).to.be(200);
        // The response body should be an array of length 2
        expect(data).to.be.a(Array);
        expect(data).to.have.length(2);
        // TODO :: Return Type [Bourreau]
        done();
      });
    });

    it('should call bourreauxIdGet successfully', function(done) {
      instance.bourreauxIdGet(1,function(error, data, response) {
        if (error) throw error;
        // The status code should be 200 
        expect(response.statusCode).to.be(200);
        // Check for expected properties and values
        // TODO :: Return Type Bourreau
        done();
      });
    });
  });

}));
