/**
 * CBRAIN API
 * REST API for interacting with the CBRAIN Platform
 *
 * OpenAPI spec version: 5.0.2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CbrainApi);
  }
}(this, function(expect, CbrainApi) {
  'use strict';

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('TagsApi', function() {
    let instance;

    beforeEach(function() {
      instance = new CbrainApi.TagsApi();
    });
    // TODO :: These endpoints retrun 401 Unauthorized
    it.skip('should call tagsGet successfully', function(done) {
      instance.tagsGet(function(error, data, response) {
        if (error) throw error;
        expect(response.status).to.be(200);
        // TODO :: Return type [Tag]
        done();
      });
    });

    it.skip('should call tagsIdDelete successfully', function(done) {
      //uncomment below and update the code to test tagsIdDelete
      //instance.tagsIdDelete(function(error) {
      //  if (error) throw error;
      //expect().to.be();
      //});
      done();
    });
    it('should call tagsIdGet successfully', function(done) {
      //uncomment below and update the code to test tagsIdGet
      //instance.tagsIdGet(function(error) {
      //  if (error) throw error;
      //expect().to.be();
      //});
      done();
    });
    it('should call tagsIdPut successfully', function(done) {
      //uncomment below and update the code to test tagsIdPut
      //instance.tagsIdPut(function(error) {
      //  if (error) throw error;
      //expect().to.be();
      //});
      done();
    });
    it('should call tagsPost successfully', function(done) {
      //uncomment below and update the code to test tagsPost
      //instance.tagsPost(function(error) {
      //  if (error) throw error;
      //expect().to.be();
      //});
      done();
    });
  });

}));
